#
---
_namespace: ieee1905_1

msgApAutoConfigurationRenew:
  _type: class
  header:
    _type: cmduHeader
    _setValue: { "messageType" : AP_AUTOCONFIGURATION_RENEW_MESSAGE }
  tlv_al_mac_tlv: tlvAlMacAddressType
  tlv_supported_role: tlvSupportedRole
  tlv_supported_freq_band: tlvSupportedFreqBand
  tlv_eof: tlvEndOfMessage