- name: feed_target_mips
  uri: https://intel.prpl.dev/intel/feed_target_mips.git
  hash: 245dca06475e84571e4ccb5e02eb4e336ba77cbe
- name: feed_datapath
  uri: https://intel.prpl.dev/intel/feed_datapath.git
  hash: 23afe7e659ed6717224659aef74af2bb11d8091a
- name: feed_ppa
  uri: https://intel.prpl.dev/intel/feed_ppa.git
  hash: 4f49fa34bbd51c7dd218df164e32c17694bed421
- name: feed_gphy_firmware
  uri: https://intel.prpl.dev/intel/feed_gphy_firmware.git
  hash: cbf75f2abde587ac2c5462d117b98e3dadaae5b6
- name: feed_switch_api
  uri: https://intel.prpl.dev/intel/feed_switch_api.git
  hash: af078af5408654ca2e759ea7afcf92163282e86e
- name: feed_wlan_6x
  uri: https://intel.prpl.dev/prplmesh/feed_wlan_6x.git
  hash: f68c49704bd518b8808167cdfea012c5d400f6d3
- name: feed_prpl
  uri: https://git.prpl.dev/prplmesh/feed-prpl.git
  hash: 89e6602655713f8487c72d8d636daa610d76a468
- name: feed_opensource_apps
  uri: https://intel.prpl.dev/prplmesh/feed_opensource_apps.git
  hash: f22c4f0b1d594598b1d38298fba513e5948dd1e4
- name: feed_pending
  uri: https://intel.prpl.dev/intel/feed-pending.git
  hash: 352365b31f968ab37e772b23c30ea32dbff9e337
